### PR TITLE
fixes #141

### LINKED ISSUE #141: STOW retry does not work with multiple DICOM destinations
The recent implementation of STOW retry (#138) does not work with a multi-DICOM destination configuration:
https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/wiki/Routing-to-multiple-DICOM-stores

### PR DESCRIPTION
**Pull request by jasonklotzer**
/gcbrun

### CODE REVIEW

File: dicom_util/src/main/java/com/google/cloud/healthcare/DicomWebClientJetty.java [hunk 1]
```diff
@@ -165,9 +160,125 @@ public void onData(Stream stream, DataFrame frame, Callback callback) {
...
+    return this.useStowOverwrite;
+  }
+
+  /**
+   * Deletes the resource and returns void.
+   *
+   * @param path The resource URL path to delete.
+   */
+  @Override
+  public void delete(String path) throws IDicomWebClient.DicomWebException {
```
Comment (jasonklotzer) [inline dicom_util/src/main/java/com/google/cloud/healthcare/DicomWebClientJetty.java:175]: Added support for delete inside of HTTP/2 code, primarily for STOW overwrite.

File: import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java [hunk 2]
```diff
@@ -121,10 +121,16 @@ public static void main(String[] args) throws IOException, GeneralSecurityExcept
...
     IDestinationClientFactory destinationClientFactory = configureDestinationClientFactory(
-        defaultCstoreDicomWebClient, credentials, flags, backupUploadService != null);
+      defaultCstoreDicomWebClient, credentials, flags, backupUploadService != null);
 
-    MultipleDestinationUploadService multipleDestinationSendService = configureMultipleDestinationUploadService(
-        flags, cstoreSubAet, backupUploadService);
+    // NOTE: This is a dependency for cStoreService if stow retry is used or if multiple
+    // destinations are leveraged, due to the backupUploadService dependency.
+    MultipleDestinationUploadService multipleDestinationSendService = null;
+    if (flags.sendToAllMatchingDestinations) {
```
Comment (jasonklotzer) [inline import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java:129]: Require explicitly setting this flag for `useStowOverwrite` to work properly, as it relied on the backupUploadService.

File: dicom_util/src/main/java/com/google/cloud/healthcare/DicomWebClientJetty.java [hunk 3]
```diff
@@ -165,9 +160,125 @@ public void onData(Stream stream, DataFrame frame, Callback callback) {
...
+  public void delete(InputStream stream) throws IDicomWebClient.DicomWebException {
+    try {
+      DicomInputStream dis = new DicomInputStream(stream);
+      Attributes attrs = dis.readDataset(-1, Tag.PixelData);
+      String instanceUrl =
+          String.format(
+              "%s/series/%s/instances/%s", // NOTE: /studies/ already in stowPath
+              attrs.getString(Tag.StudyInstanceUID, 0),
+              attrs.getString(Tag.SeriesInstanceUID, 0),
+              attrs.getString(Tag.SOPInstanceUID, 0));
```
Comment (danielbeaudreau) [inline dicom_util/src/main/java/com/google/cloud/healthcare/DicomWebClientJetty.java:277]: Nit: instead of defaulting to a 0 value and potentially deleting something we're not supposed to (instance with IDs of 0), can we throw an exception if these are not found?

File: import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java [hunk 4]
```diff
@@ -157,15 +163,12 @@ private static IDicomWebClient configureDefaultDicomWebClient(
       GoogleCredentials credentials,
       Flags flags) {
     IDicomWebClient defaultCstoreDicomWebClient;
+    log.debug("--stow_overwrite set to " + (flags.useStowOverwrite ? "true" : "false"));
```
Comment (danielbeaudreau) [inline import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java:166]: nit: instead of having these debug statements in various places, we could have one function that logs the flags state for all of the flags in one place / function.

File: import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java (hunk 2 above)
Comment (danielbeaudreau) [reply import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java:129]: Trying to reason about this change a bit: it looks like the state before was, we set the multipleDestinationSendService to null only if the backupService was null. Now we set it to null if sendToAllMatchingDestinations is false. 

I'm wondering, isn't this a breaking change in some ways? E.g. for current users who set up the backupService but do not configure sendToAllMatchingDestinations, won't their backups break now?

**Review by danielbeaudreau — CHANGES_REQUESTED** [review]

File: import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java (hunk 4 above)
Comment (jasonklotzer) [reply import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java:166]: Added issue #143 for this. Removed the debug statement for now.

File: dicom_util/src/main/java/com/google/cloud/healthcare/DicomWebClientJetty.java (hunk 3 above)
Comment (jasonklotzer) [reply dicom_util/src/main/java/com/google/cloud/healthcare/DicomWebClientJetty.java]: Resolved in latest commmit

File: import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java (hunk 2 above)
Comment (jasonklotzer) [reply import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java]: Reverted the initialization logic and added a check for multiple destinations + stow retry later in the code.

File: import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java [hunk 5]
```diff
@@ -190,16 +186,22 @@ private static IDestinationClientFactory configureDestinationClientFactory(
...
           multipleDestinations.getLeft(),
           multipleDestinations.getRight(),
           defaultCstoreDicomWebClient);
     } else { // with or without backup usage.
+      if ((flags.destinationConfigPath != null || flags.destinationConfigInline != null)
+          && flags.useStowOverwrite) {
+        throw new IllegalArgumentException(
+            "Must use '--send_to_all_matching_destinations' when using '--stow_overwrite' and"
+                + " providing a destination config.");
+      }
```
Comment (danielbeaudreau) [inline import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java:201]: I looked in the cstore service to refresh my memory. So it looks like the condition for this to work is multipleDestinationSendService != null && useStowOverwrite = true, that way we take the path where we use the backup service, and can use the delete and re-store logic. [1] Just wondering why it matters if --send_to_all_matching_destinations is true vs. just using one destination here? 

Can we simplify this check to:
if multipleDestinationSendService == null && useStowOverWrite, then throw error.

[1] https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/blob/c893c51a4cce514e10511fb9d53f9205e60c2f17/import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/CStoreService.java#L119

Comment (jasonklotzer) [reply import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java:201]: Two reasons: 
1) The import adapter always [initializes](https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/blob/master/import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/CStoreService.java#L129) the multipleDestinationSendService, so it won't be `null`.
2) This one took me a bit of time to understand, but this [code](https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/blob/master/import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java#L181) initializes the `destinationClientFactory` based on send_to_all_matching_destinations, and then the the `Single/MultipleDestinationClientFactory` will assign the destination to the `DestinationHolder` based on the C-store requests. The problem is the single/multiple implementations actually assign the values based on different properties and the values have to be retrieved via different properties (namely `getSingleDestination()` vs `getHealthcareDestinations()`). And then this [code](https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/blob/master/import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/CStoreService.java#L129) relies on the `DestinationHolder` (though `multipleSendService` will never be null in import adapter mode).

Comment (danielbeaudreau) [reply import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java:201]: For 1. It looks like we do sometimes not initialize multipleDestinationSendService, if backupUploadService == null: 
https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/blob/195a0af70b1fed12df24575fad7b1375faff63d5/import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java#L220

For 2. hmm this is interesting. So it looks like there's a bug in the code? When:
- the single destination client factory is specified
- backup service is initialized
- but sendToAllMatchingDatasets is not specified

then we will use multipleDestinationSendService and call destinationHolder.getHealthcareDestinations() in CStoreService.Java.
However destinationHolder.getHealthcareDestinations() will not return what we expect, since single destination client factory only returns anything on getSingleDestination().

Comment (danielbeaudreau) [reply import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java:201]: The bug in 2. being that we would just be sending to all destinations rather than the single destination that we intended to send based on the filter. And the filtering in the single destination would not work. 

Am I correct? The code is a bit complex here so I could have got this wrong. Anyway I think that issue is outside of the scope of this PR, but I wanted to get on the same page with this before deciding what to do about it.

Comment (jasonklotzer) [reply import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java:201]: As discussed, going to leave the code as-is for now. Created issue #144 for 2.
